// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// Auto-generated by swift-openapi-bootstrapper
// Generated at: 2026-02-21T12:01:37.975275

import PackageDescription

let package = Package(
    name: "ElevenLabs",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
        .tvOS(.v16),
        .watchOS(.v9),
    ],
    products: [
        .library(
            name: "ElevenLabsTypes",
            targets: ["ElevenLabsTypes"]
        ),
        .library(
            name: "ElevenLabs",
            targets: ["ElevenLabs"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-openapi-generator.git", from: "1.10.0"),
        .package(url: "https://github.com/apple/swift-openapi-runtime.git", from: "1.8.0"),
        .package(url: "https://github.com/swift-server/swift-openapi-async-http-client", from: "1.1.0"),
        .package(url: "https://github.com/atacan/UsefulThings", branch: "main"),
    ],
    targets: [
        // Types target: Contains generated types from OpenAPI spec
        .target(
            name: "ElevenLabsTypes",
            dependencies: [
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime")
            ]
        ),
        // Client target: Contains generated client and custom code
        .target(
            name: "ElevenLabs",
            dependencies: [
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "OpenAPIAsyncHTTPClient", package: "swift-openapi-async-http-client"),
                .target(name: "ElevenLabsTypes"),
            ]
        ),
        // Tests
        .testTarget(
            name: "ElevenLabsTests",
            dependencies: [
                .target(name: "ElevenLabs"),
                .product(name: "UsefulThings", package: "UsefulThings"),
            ]
        ),
    ]
)
